version: "3.8"

services: 
    backend:
          container_name: "rest_api"
          restart: on-failure
          build: 
            context: "./"
            dockerfile: Dockerfile
          ports:
            - 8000:8080
          volumes:
            - ./backend/api:/usr/src/app/
          depends_on: 
            - db
          networks: 
            - fullstack      
    db:
          image: postgres
          container_name: "database"
          restart: always
          environment: 
               POSTGRES_PASSWORD: admin
          volumes: 
              - ./backend/.dbdata:/var/lib/postgresql/data
          ports: 
              - 54032:5432
          networks: 
              - fullstack

volumes:
  backend: 
  api:

networks: 
  fullstack:
    driver: bridge