version: "3.8"

services: 
    backend:
          container_name: "rest_api"
          restart: on-failure
          build: 
            context: "./"
            dockerfile: Dockerfile
          environment:
            - DB_PASSWORD=postgres
            - MYSQL_DATABASE=postgres
            - DB_HOST=db
            - DB_USER=postgres
            - DB_PORT=5432
            - DB_NAME=postgres
          ports:
            - 8000:8080
          volumes:
            - ./:/usr/src/app/
          depends_on: 
            - db
          networks: 
            - fullstack      
    db:
          image: postgres
          container_name: "database"
          restart: always
          environment: 
               POSTGRES_USER: postgres
               POSTGRES_PASSWORD: postgres
               POSTGRES_DB: postgres
               PGDATA: /var/lib/postgresql/data
          volumes: 
              - ./.dbdata:/var/lib/postgresql/data
          ports: 
              - 5432:5432
          networks: 
              - fullstack

volumes:
  backend: 
  api:

networks: 
  fullstack:
    driver: bridge