apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-postgres-beer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: pg
  template:
    metadata:
      labels:
        bb: pg
    spec:
      containers:
        - name: container-postgres-beer
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: config-pg-beer
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: config-pg-beer
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: config-pg-beer
                  key: POSTGRES_DB
